on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Run WDIO tests
    steps:
    - name: Start selenoid
      uses: Xotabu4/selenoid-github-action@v1
    - uses: actions/checkout@v1
    - run: npm ci  
    - name: Run tests
      run: npm test.ga